vtx_sel: ( acos(cos(SDVSecVtx_L_phi-MET_phi))<1.5 )&&(SDVSecVtx_pAngle>0.2)&&(SDVSecVtx_nGoodTrack>=2)&&( acos(cos(SDVSecVtx_L_phi-Jet_phi[0]))>1 ) && (SDVSecVtx_ndof>1)
vtx_sel_val: ( acos(cos(SDVSecVtx_L_phi-MET_phi))<1.5 )&&(SDVSecVtx_pAngle>0.2)&&(SDVSecVtx_nGoodTrack==1)&&( acos(cos(SDVSecVtx_L_phi-Jet_phi[0]))>1 ) && (SDVSecVtx_ndof>1)
muon_sel: (Muon_looseId>0) && (Muon_eta<2.4) && (Muon_pt>10)
ele_sel: (Electron_cutBased>=1) && (Electron_eta<2.5) && (Electron_pt>10)
photon_sel: (Photon_cutBased>=1) && (Photon_eta<2.5) && (Photon_pt>15)
tau_sel: (Tau_idDecayModeOldDMs>=1) && (Tau_eta<2.3) && (Tau_pt>18)
#presel: MET_pt>200&&HLT_PFMET120_PFMHT120_IDTight && Jet_pt[0]>100 && Flag_METFilters && Jet_chHEF[0]>0.1 && Jet_neHEF[0]<0.8
presel: MET_pt>200 && HLT_PFMETNoMu120_PFMHTNoMu120_IDTight && Jet_pt[0]>100 && Flag_goodVertices && Flag_globalSuperTightHalo2016Filter && Flag_HBHENoiseFilter && Flag_HBHENoiseIsoFilter && Flag_EcalDeadCellTriggerPrimitiveFilter && Flag_BadPFMuonFilter && Flag_BadPFMuonDzFilter && Flag_hfNoisyHitsFilter && Flag_BadChargedCandidateFilter && Flag_eeBadScFilter && Flag_ecalBadCalibFilter && Jet_chHEF[0]>0.1 && Jet_neHEF[0]<0.8 

new_variables:
  SDVTrack_isInSV: Track_isInSV(SDVIdxLUT_TrackIdx,nSDVTrack)
  SDVTrack_qoverp: SDVTrack_charge/SDVTrack_pt
  SDVTrack_dxySig: abs(SDVTrack_dxy)/SDVTrack_dxyError
  SDVTrack_dzSig: abs(SDVTrack_dz)/SDVTrack_dzError
  SDVTrack_ptqual: SDVTrack_ptError/SDVTrack_pt
  SDVTrack_dphi_jet0: acos(cos(SDVTrack_phi-Jet_phi[0]))
  SDVTrack_deta_jet0: abs(SDVTrack_eta-Jet_eta[0])
  SDVTrack_dR_jet0: sqrt(SDVTrack_dphi_jet0*SDVTrack_dphi_jet0 + SDVTrack_deta_jet0*SDVTrack_deta_jet0)
  SDVTrack_dphi_MET: acos(cos(SDVTrack_phi-MET_phi))
  SDVTrack_dxydzratio: abs(SDVTrack_dxy/SDVTrack_dz)
  SDVTrack_isGoodTrack: ( (abs(SDVTrack_dxy)/SDVTrack_dxyError)>4 ) && (SDVTrack_normalizedChi2 < 5) && (SDVTrack_numberOfValidHits>13) && ( (SDVTrack_ptError/SDVTrack_pt)<0.015 ) && ( SDVTrack_dxydzratio>0.25 ) && ( acos(cos(SDVTrack_phi-Jet_phi[0]))>1 ) && ( acos(cos(SDVTrack_phi-MET_phi))<1.5 ) && (SDVTrack_pfRelIso03_all<5)
  SDVSecVtx_nGoodTrack: SDVSecVtx_nGoodTrack(SDVIdxLUT_SecVtxIdx,SDVIdxLUT_TrackIdx,SDVTrack_isGoodTrack,nSDVSecVtx)
  SDVSecVtx_dphiMET: 'acos(cos(SDVSecVtx_L_phi-MET_phi))'
  SDVSecVtx_dphijet0: 'acos(cos(SDVSecVtx_L_phi-Jet_phi[0]))'
  nSDVSecVtx_sel: ['Sum({0})', vtx_sel]
  nSDVSecVtx_sel_val: ['Sum({0})', vtx_sel_val]
  nMuon_sel: ['Sum({0})', muon_sel]
  nEle_sel: ['Sum({0})', ele_sel]
  nPhoton_sel: ['Sum({0})', photon_sel]
  nTau_sel: ['Sum({0})', tau_sel]
  SDVSecVtx_LxySig_max_val: ['Max(SDVSecVtx_LxySig[{0}])',vtx_sel_val]
  SDVSecVtx_LxySig_max: ['Max(SDVSecVtx_LxySig[{0}])',vtx_sel]
  #SDVSecVtx_LxySig_MLsel_max: ['Max(SDVSecVtx_LxySig[{0}])',vtx_sel_ML]
regions:
  All: 
  presele: nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0
  VR: nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0 && nSDVSecVtx_sel_val>0 && nSDVSecVtx_sel==0 && MET_pt>700 && SDVSecVtx_LxySig_max>20.0
  VR_CRlowMET: nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0 && nSDVSecVtx_sel_val>0 && nSDVSecVtx_sel==0 && MET_pt<700 && SDVSecVtx_LxySig_max>20.0
  VR_CRlowLxy: nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0 && nSDVSecVtx_sel_val>0 && nSDVSecVtx_sel==0 && MET_pt>700 && SDVSecVtx_LxySig_max<20.0
  VR_CRlowLxylowMET: nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0 && nSDVSecVtx_sel_val>0 && nSDVSecVtx_sel==0 && MET_pt<700 && SDVSecVtx_LxySig_max<20.0
  SR_CRlowMET: nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0 && nSDVSecVtx_sel>0 && MET_pt<700 && SDVSecVtx_LxySig_max>20.0
  SR_CRlowLxy: nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0 && nSDVSecVtx_sel>0 && MET_pt>700 && SDVSecVtx_LxySig_max<20.0
  SR_CRlowLxylowMET: nMuon_sel==0 && nEle_sel==0 && nPhoton_sel==0 && nTau_sel==0 && nSDVSecVtx_sel>0 && MET_pt<700 && SDVSecVtx_LxySig_max<20.0
event_variables:
- nSDVSecVtx_sel
- nSDVSecVtx_sel_val
- nMuon_sel
- nEle_sel
- nPhoton_sel
- nTau_sel
- MET_pt
- SDVSecVtx_LxySig_max
event_2d_plots:
  - [MET_pt,SDVSecVtx_LxySig_max]
objects:
  SDVSecVtx:
    selections:
      all:
      sel_val: ( acos(cos(SDVSecVtx_L_phi-MET_phi))<1.5 )&&(SDVSecVtx_LxySig>=20.)&&(SDVSecVtx_pAngle>0.2)&&(SDVSecVtx_nGoodTrack==1)&&( acos(cos(SDVSecVtx_L_phi-Jet_phi[0]))>1 ) && (SDVSecVtx_ndof>1)
      sel: ( acos(cos(SDVSecVtx_L_phi-MET_phi))<1.5 )&&(SDVSecVtx_LxySig>=20.)&&(SDVSecVtx_pAngle>0.2)&&(SDVSecVtx_nGoodTrack>=2)&&( acos(cos(SDVSecVtx_L_phi-Jet_phi[0]))>1 ) && (SDVSecVtx_ndof>1)
    variables:
    - SDVSecVtx_x
    - SDVSecVtx_y
    - SDVSecVtx_nTracks
    - SDVSecVtx_pAngle
    - SDVSecVtx_nGoodTrack
    - SDVSecVtx_dlen
    - SDVSecVtx_dlenSig
    - SDVSecVtx_dlen_err
    - SDVSecVtx_Lxy
    - SDVSecVtx_LxySig
    - SDVSecVtx_Lxy_err
    - SDVSecVtx_chi2
    - SDVSecVtx_normalizedChi2
    - SDVSecVtx_ndof
    - SDVSecVtx_dphiMET
    - SDVSecVtx_dphijet0
    2d_plots:
    - [SDVSecVtx_Lxy,SDVSecVtx_pAngle]
    - [SDVSecVtx_x,SDVSecVtx_y]
  SDVTrack:
    selections:
      all: 
      GoodTrack: SDVTrack_dxySig>4 && SDVTrack_normalizedChi2<5 && SDVTrack_numberOfValidHits>13 && SDVTrack_ptqual < 0.015 && ( SDVTrack_dxydzratio>0.25 ) && (SDVTrack_pfRelIso03_all<5) && ( acos(cos(SDVTrack_phi-Jet_phi[0]))>1 ) && ( acos(cos(SDVTrack_phi-MET_phi))<1.5 )
      allInSV: SDVTrack_isInSV==1
      GoodTrackdxydzInSV: SDVTrack_dxySig>4 && SDVTrack_normalizedChi2<5 && SDVTrack_numberOfValidHits>13 && SDVTrack_ptqual < 0.015 && SDVTrack_dxydzratio>0.25 && ( acos(cos(SDVTrack_phi-Jet_phi[0]))>1 ) && ( acos(cos(SDVTrack_phi-MET_phi))<1.5 ) && SDVTrack_isInSV==1
    variables:
    - SDVTrack_dxy
    - SDVTrack_dxyError
    - SDVTrack_dxySig
    - SDVTrack_dz
    - SDVTrack_dzError
    - SDVTrack_dzSig
    - SDVTrack_normalizedChi2
    - SDVTrack_numberOfValidHits
    - SDVTrack_pt
    - SDVTrack_ptError
    - SDVTrack_ptqual
    - SDVTrack_dxydzratio
    - SDVTrack_dphi_MET
    - SDVTrack_dphi_jet0
    - SDVTrack_dR_jet0
    - SDVTrack_pfRelIso03_all
    - SDVTrack_pfRelIso03_chg
    2d_plots:

    nm1:
    - ['SDVTrack_pfRelIso03_all','<5']
    - ['SDVTrack_dxySig','>4']
    - ['SDVTrack_normalizedChi2','<5']
    - ['SDVTrack_numberOfValidHits','>13']
    - ['SDVTrack_ptqual','<0.015']
    - ['SDVTrack_dxydzratio','>0.25']
    - ['SDVTrack_dphi_MET','<1.5']
    - ['SDVTrack_dphi_jet0','>1']

plot_setting:
  LHE_HT: [LHE_HT, ';LHE HT (GeV);A.U.', 500, 0, 5000]
  MET_pt: [MET_pt, ';MET (GeV);A.U.', 100, 0, 1000]
  SDVTrack_dxy: [SDVTrack_dxy, ";track dxy (cm);A.U.",400,-20,20]
  SDVTrack_dxyError: [SDVTrack_dxyError,";track #sigma dxy (cm);A.U.",100,0,1]
  SDVTrack_dxySig: [SDVTrack_dxySig,";track |dxy/#sigma dxy|;A.U.",500,0,100]
  SDVTrack_dz: [SDVTrack_dz,";track dz (cm);A.U.",400,-20,20]
  SDVTrack_dzError: [SDVTrack_dzError,";track #sigma dz (cm);A.U.",100,0,1] 
  SDVTrack_dzSig: [SDVTrack_dzSig,";track |dz/#sigma dz|;A.U.",500,0,100]
  SDVTrack_normalizedChi2: [SDVTrack_normalizedChi2,";track norm Chi2;A.U.",100,0,5]
  SDVTrack_numberOfValidHits: [SDVTrack_numberOfValidHits,";track # valid hits;A.U.",50,0,50]
  SDVTrack_pt: [SDVTrack_pt,";track pt (GeV);A.U.",100,0,50]
  SDVTrack_ptError: [SDVTrack_ptError,";track #sigma pt (GeV);A.U.",100,0,0.5]
  SDVTrack_ptqual: [SDVTrack_ptqual,";track #sigma pt/pt;A.U.",100,0,0.02]
  SDVTrack_dxydzratio: [SDVTrack_dxydzratio,";track |dxy/dz|;A.U.",100,0,1]
  SDVTrack_dphi_MET: [SDVTrack_dphi_MET,";#Delta #phi (track,MET);A.U.",64,0,3.2]
  SDVTrack_dphi_jet0: [SDVTrack_dphi_jet0,";#Delta #phi (track,jet0);A.U.",64,0,3.2]
  SDVTrack_dR_jet0: [SDVTrack_dR_jet0,";#Delta R (track,jet0);A.U.",100,0,5]
  SDVTrack_dr03TkSumPt: [SDVTrack_dr03TkSumPt,";track dR03TkSumPt;A.U.",200,0,100]
  SDVTrack_pfAbsIso03_all: [SDVTrack_pfAbsIso03_all, ";track absolute iso all;A.U.",200,0,100]
  SDVTrack_pfAbsIso03_chg: [SDVTrack_pfAbsIso03_chg, ";track absolute iso chg;A.U.",200,0,100]
  SDVTrack_pfRelIso03_all: [SDVTrack_pfRelIso03_all, ";track relative iso all;A.U.",200,0,100]
  SDVTrack_pfRelIso03_chg: [SDVTrack_pfRelIso03_chg, ";track relative iso chg;A.U.",200,0,100]
  SDVTrack_pfAbsIso03_all_mod: [SDVTrack_pfAbsIso03_all_mod, ";track absolute iso all;A.U.",200,0,100]
  SDVTrack_pfAbsIso03_chg_mod: [SDVTrack_pfAbsIso03_chg_mod, ";track absolute iso chg;A.U.",200,0,100]
  SDVTrack_pfRelIso03_all_mod: [SDVTrack_pfRelIso03_all_mod, ";track relative iso all;A.U.",200,0,100]
  SDVTrack_pfRelIso03_chg_mod: [SDVTrack_pfRelIso03_chg_mod, ";track relative iso chg;A.U.",200,0,100]
  SDVTrack_ntk_dRcone: [SDVTrack_ntk_dRcone, ";track ntk in dR cone;A.U.",40,0,40]
  SDVTrack_sumpt_dRcone: [SDVTrack_sumpt_dRcone, ";track sumpt in dR cone;A.U.",100,0,50]
  SDVTrack_weight: [SDVTrack_weight, ";track weight;A.U.",100,0,1]
  SDVTrack_minJetdphi: [SDVTrack_minJetdphi,";min(#Delta#phi(track, jet));A.U.",64,0,3.2]
  SDVTrack_minJetdeta: [SDVTrack_minJetdeta,";min(#Delta#eta(track, jet));A.U.",100,0,5]
  SDVTrack_minJetdR: [SDVTrack_minJetdR,";min(#DeltaR(track, jet));A.U.",100,0,5]
  SDVTrack_minJetdR_pt: [SDVTrack_minJetdR_pt,";pt of jet with minimum dR with track;A.U.",100,0,100]
  SDVTrack_dxy_InSV: [SDVTrack_dxy_InSV, ";track dxy (cm);A.U.",400,-20,20]
  SDVTrack_dxyError_InSV: [SDVTrack_dxyError_InSV,";track #sigma dxy (cm);A.U.",100,0,1]
  SDVTrack_dxySig_InSV: [SDVTrack_dxySig_InSV,";track |dxy/#sigma dxy|;A.U.",500,0,100]
  SDVTrack_dz_InSV: [SDVTrack_dz_InSV,";track dz (cm);A.U.",400,-20,20]
  SDVTrack_dzError_InSV: [SDVTrack_dzError_InSV,";track #sigma dz (cm);A.U.",100,0,1] 
  SDVTrack_dzSig_InSV: [SDVTrack_dzSig_InSV,";track |dz/#sigma dz|;A.U.",500,0,100]
  SDVTrack_normalizedChi2_InSV: [SDVTrack_normalizedChi2_InSV,";track norm Chi2;A.U.",100,0,5]
  SDVTrack_numberOfValidHits_InSV: [SDVTrack_numberOfValidHits_InSV,";track # valid hits;A.U.",50,0,50]
  SDVTrack_pt_InSV: [SDVTrack_pt_InSV,";track pt (GeV);A.U.",100,0,50]
  SDVTrack_ptError_InSV: [SDVTrack_ptError_InSV,";track #sigma pt (GeV);A.U.",100,0,0.5]
  SDVTrack_ptqual_InSV: [SDVTrack_ptqual_InSV,";track #sigma pt/pt;A.U.",100,0,0.02]
  SDVTrack_dxydzratio_InSV: [SDVTrack_dxydzratio_InSV,";track |dxy/dz|;A.U.",100,0,1]
  SDVTrack_dphi_MET_InSV: [SDVTrack_dphi_MET_InSV,";#Delta #phi (track,MET);A.U.",64,0,3.2]
  SDVTrack_dphi_jet0_InSV: [SDVTrack_dphi_jet0_InSV,";#Delta #phi (track,jet0);A.U.",64,0,3.2]
  SDVTrack_dr03TkSumPt_InSV: [SDVTrack_dr03TkSumPt,";track dR03TkSumPt;A.U.",200,0,100]
  SDVTrack_pfAbsIso03_all_InSV: [SDVTrack_pfAbsIso03_all_InSV, ";track absolute iso all;A.U.",200,0,100]
  SDVTrack_pfAbsIso03_chg_InSV: [SDVTrack_pfAbsIso03_chg_InSV, ";track absolute iso chg;A.U.",200,0,100]
  SDVTrack_pfRelIso03_all_InSV: [SDVTrack_pfRelIso03_all_InSV, ";track relative iso all;A.U.",200,0,100]
  SDVTrack_pfRelIso03_chg_InSV: [SDVTrack_pfRelIso03_chg_InSV, ";track relative iso chg;A.U.",200,0,100]
  SDVRefitTrack_dxy: [SDVRefitTrack_dxy, ";track dxy (cm);A.U.",400,-20,20]
  SDVRefitTrack_dxyError: [SDVRefitTrack_dxyError,";track #sigma dxy (cm);A.U.",100,0,1]
  SDVRefitTrack_dxySig: [SDVRefitTrack_dxySig,";track |dxy/#sigma dxy|;A.U.",500,0,100]
  SDVRefitTrack_dz: [SDVRefitTrack_dz,";track dz (cm);A.U.",400,-20,20]
  SDVRefitTrack_dzError: [SDVRefitTrack_dzError,";track #sigma dz (cm);A.U.",100,0,1] 
  SDVRefitTrack_dzSig: [SDVRefitTrack_dzSig,";track |dz/#sigma dz|;A.U.",500,0,100]
  SDVRefitTrack_normalizedChi2_new: [SDVRefitTrack_normalizedChi2_new,";track norm Chi2;A.U.",100,0,5]
  SDVRefitTrack_numberOfValidHits_new: [SDVRefitTrack_numberOfValidHits_new,";track # valid hits;A.U.",50,0,50]
  SDVRefitTrack_pt: [SDVRefitTrack_pt,";track pt (GeV);A.U.",100,0,50]
  SDVRefitTrack_ptError: [SDVRefitTrack_ptError,";track #sigma pt (GeV);A.U.",100,0,0.5]
  SDVRefitTrack_ptqual: [SDVRefitTrack_ptqual,";track #sigma pt/pt;A.U.",100,0,0.02]
  SDVRefitTrack_dxydzratio: [SDVRefitTrack_dxydzratio,";track |dxy/dz|;A.U.",100,0,1]
  SDVRefitTrack_dphi_MET: [SDVRefitTrack_dphi_MET,";#Delta #phi (track,MET);A.U.",64,0,3.2]
  SDVRefitTrack_dphi_jet0: [SDVRefitTrack_dphi_jet0,";#Delta #phi (track,jet0);A.U.",64,0,3.2]
  SDVRefitTrack_dr03TkSumPt: [SDVRefitTrack_dr03TkSumPt,";track dR03TkSumPt;A.U.",200,0,100]
  SDVRefitTrack_pfRelIso03_all: [SDVRefitTrack_pfRelIso03_all, ";track iso all;A.U.",200,0,100]
  SDVRefitTrack_pfRelIso03_chg: [SDVRefitTrack_pfRelIso03_chg, ";track iso chg;A.U.",200,0,100]
  SDVSecVtx_x: [SDVSecVtx_x, ';vertex x (cm);A.U.',400, -20, 20]
  SDVSecVtx_y: [SDVSecVtx_y, ';vertex y (cm);A.U.',400, -20, 20]
  SDVSecVtx_L_eta_abs: [SDVSecVtx_L_eta_abs, ';vertex |#eta|;A.U.', 200, 0, 10]
  SDVSecVtx_Lxy: [SDVSecVtx_Lxy, ';vertex L_{xy} (cm);A.U.', 100, 0, 10]
  SDVSecVtx_LxySig: [SDVSecVtx_LxySig, ';vertex L_{xy}/#sigmaL_{xy};A.U.', 500, 0, 100]
  SDVSecVtx_LxySig_max: [SDVSecVtx_LxySig_max, ';max vertex L_{xy}/#sigma_{L_{xy}};A.U.', 100, 0, 100]
  SDVSecVtx_Lxy_err: [SDVSecVtx_Lxy_err, ';vertex #sigmaL_{xy} (cm);A.U.', 100, 0, 0.5]
  SDVSecVtx_ParTScore: [SDVSecVtx_ParTScore, ';ParTScore;A.U.', 50, 0, 1]
  SDVSecVtx_TkMaxdR: [SDVSecVtx_TkMaxdR, ';vertex track max(dR);A.U.', 100, 0, 5]
  SDVSecVtx_TkMaxdeta: [SDVSecVtx_TkMaxdeta, ';vertex track max(d#eta);A.U.', 100, 0, 5]
  SDVSecVtx_TkMaxdphi: [SDVSecVtx_TkMaxdphi, ';vertex track max(d#phi);A.U.', 64, 0, 3.2]
  SDVSecVtx_TkMindR: [SDVSecVtx_TkMindR, ';vertex track min(dR);A.U.', 100, 0, 5]
  SDVSecVtx_TkMindeta: [SDVSecVtx_TkMindeta, ';vertex track min(d#eta);A.U.', 100, 0, 5]
  SDVSecVtx_TkMindphi: [SDVSecVtx_TkMindphi, ';vertex track min(d#phi);A.U.', 64, 0, 3.2]
  SDVSecVtx_chi2: [SDVSecVtx_chi2, ';vertex chi2;A.U.', 50, 0, 10]
  SDVSecVtx_dlen: [SDVSecVtx_dlen, ';vertex dlen (cm);A.U.', 100, 0, 10]
  SDVSecVtx_dlenSig: [SDVSecVtx_dlenSig, ';vertex dlen/#sigmadlen;A.U.', 500, 0, 100]
  SDVSecVtx_dlen_err: [SDVSecVtx_dlen_err, ';vertex #sigmadlen (cm);A.U.', 100, 0, 0.5]
  SDVSecVtx_dphiMET: [SDVSecVtx_dphiMET, ';#Delta#phi(Lxy,MET)', 64, 0, 3.2]
  SDVSecVtx_dphijet0: [SDVSecVtx_dphijet0, ';#Delta#phi(Lxy,jet0)', 64, 0, 3.2]
  SDVSecVtx_matchedLLPIdx_bydau: [SDVSecVtx_matchedLLPIdx_bydau, ';vertex matched LLP idx;A.U.', 5, -1, 4]
  SDVSecVtx_matchedLLPnDau_bydau: [SDVSecVtx_matchedLLPnDau_bydau, ';vertex number of tracks matched with LLP;A.U.', 10, 0, 10]
  SDVSecVtx_nGoodTrack: [SDVSecVtx_nGoodTrack, ';vertex ngoodTrack;A.U.', 20, 0, 20]
  SDVSecVtx_nGoodRefitTrack: [SDVSecVtx_nGoodRefitTrack, ';vertex ngoodRefitTrack;A.U.', 20, 0, 20]
  SDVSecVtx_nTracks: [SDVSecVtx_nTracks, ';vertex nTracks;A.U.', 20, 0, 20]
  SDVSecVtx_ndof: [SDVSecVtx_ndof, ';vertex ndof;A.U.', 20, 0, 20]
  SDVSecVtx_normalizedChi2: [SDVSecVtx_normalizedChi2, ';vertex norm chi2;A.U.', 50, 0, 10]
  SDVSecVtx_pAngle: [SDVSecVtx_pAngle, ';vertex pAngle;A.U.', 64, 0, 3.2]
  nSDVSecVtx_sel: [nSDVSecVtx_sel, ';Number of vertices;A.U.', 20, 0, 20]
  nSDVSecVtx_sel_val: [nSDVSecVtx_sel_val, ';Number of vertices;A.U.', 20, 0, 20]
  nSDVSecVtx_sel_gen: [nSDVSecVtx_sel_gen, ';Number of vertices (with gen cut);A.U.', 20, 0, 20]
  Pileup_nPU: [Pileup_nPU,';nPU;A.U.',100,0,100]
  nMuon_sel: [nMuon_sel,';nMuons;A.U.',10,0,10]
  nEle_sel: [nEle_sel,';nEle;A.U.',10,0,10]
  nPhoton_sel: [nPhoton_sel,';nPhoton;A.U.',10,0,10]
  nTau_sel: [nTau_sel,';nTau;A.U.',10,0,10]

